Some stuff that came up as usability concerns
Zoybean/Functional pull request #1
Opened 2019-05-31 13:09 UTC by noneuclideangirl

Consolidated terminology (`Maybe` wasn't up to date with `bind` --> `andThen`). Added `ok` and `err` to `Result` (a la Rust). Added `orElse` to `Result`. Replaced `match` overloads with `matchThen`, so that the type inferencing doesn't get confused.

I didn't add any new test cases, sorry!

2019-06-16 12:05 UTC, Zoybean requested changes

2019-06-16 12:05 UTC, Zoybean commented on src/main/java/functional/algebraic/Maybe.java
> -    public static <V> Maybe<V> of(@Nullable V value)
Keep these annotations, they were intentionally added to denote that this is one of few places where a null value is acceptable as a parameter.

2019-06-16 12:05 UTC, Zoybean commented on src/main/java/functional/algebraic/Result.java
> +    public void collapse(Consumer<Object> f) {
This would also be valuable if implemented in `Either`, and this implementation can delegate to it.

2019-06-16 12:05 UTC, Zoybean commented on src/main/java/functional/algebraic/Maybe.java
> + * @author Eleanor McMurtry (renamed match overloads to avoid inference errors)
Remove comment on why you're listed as an author. I'm happy to share credit, and people can check the blame for specific feature authorship.
```suggestion
 * @author Eleanor McMurtry
```

2019-06-16 12:05 UTC, Zoybean commented on src/main/java/functional/algebraic/Maybe.java
> +     * Consumes the value inside this Result, if there is one.
```suggestion
     * Consumes the value inside this Maybe, if there is one.
```

2019-06-16 12:05 UTC, Zoybean commented on src/main/java/functional/algebraic/Result.java
> +        return either.matchThen(ignored -> defaultValue, val -> val);
Multiline match expressions are preferred for their similarity to haskell `case` syntax; as well as double underscore (`__`) for ignored variables.
```suggestion
        return either.matchThen(
            __ -> defaultValue,
            val -> val
        );
```

2019-06-16 12:05 UTC, Zoybean commented on src/main/java/functional/algebraic/Result.java
> +    public Result<E, V> ok(Consumer<? super V> op) {
I think I'd prefer this be called `ifOk` to clarify that it performs a conditional operation. Also to prevent name collision if I change the constructor names
```suggestion
    public Result<E, V> ifOk(Consumer<? super V> op) {
```

2019-06-16 12:05 UTC, Zoybean commented on src/main/java/functional/algebraic/Result.java
> +    public Result<E, V> err(Consumer<? super E> op) {
```suggestion
    public Result<E, V> ifErr(Consumer<? super E> op) {
```

2019-06-16 12:05 UTC, Zoybean commented on src/main/java/functional/algebraic/Result.java
> +    public V consumeError(Function<? super E, ? extends V> f) {
Given the name similarity to `Maybe::consume`, and the fact that this does not involve a `Consumer`, maybe `convert`, `transform` or `transmute` would be better?
```suggestion
    public V convertError(Function<? super E, ? extends V> f) {
```

2019-06-16 13:27 UTC, noneuclideangirl commented on src/main/java/functional/algebraic/Result.java
> +    public Result<E, V> ok(Consumer<? super V> op) {
I'm fine with this, ok() was chosen for symmetry with Rust though.

2019-06-17 01:18 UTC, Zoybean commented on src/main/java/functional/algebraic/Result.java
> +    public Result<E, V> ok(Consumer<? super V> op) {
Doesn't rust's `ok()` method just return an `Option<V>`? The version of the docs I'm looking at indicates that

2019-06-17 01:20 UTC, noneuclideangirl commented on src/main/java/functional/algebraic/Result.java
> +    public Result<E, V> ok(Consumer<? super V> op) {
Oh, it does too! Sounds good.

2019-06-17 01:25 UTC, noneuclideangirl commented on src/main/java/functional/algebraic/Maybe.java
> -    public static <V> Maybe<V> of(@Nullable V value)
Resolved in latest push

2019-06-17 01:26 UTC, noneuclideangirl commented on src/main/java/functional/algebraic/Result.java
> +    public void collapse(Consumer<Object> f) {
Resolved in latest push

2019-06-18 12:42 UTC, merged